import { Header, Stack, ThemeProvider } from "@/components";
import { theme } from "@/config";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <ThemeProvider theme={theme}>
          <Stack>
            <Header />
            <Stack>{children}</Stack>
          </Stack>
        </ThemeProvider>
      </body>
    </html>
  );
}
