import "./globals.css";
import { ThemeProvider, Stack, Header } from "@/components";
import { theme } from "@/config";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <ThemeProvider theme={theme}>
          <Stack sx={{ paddingLeft: { xs: "102px" } }}>
            <Header />
            <Stack sx={{ padding: { xs: "16px", md: "24px" } }}>
              {children}
            </Stack>
          </Stack>
        </ThemeProvider>
      </body>
    </html>
  );
}
