import { Avatar, Box, Divider, MenuLinks, MenuWrapper } from "@/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
  params: { id },
}: {
  children: React.ReactNode;
  params: { id: string };
}) {
  return (
    <>
      <MenuWrapper>
        <Avatar sx={{ width: { xs: "none", sm: "visible" } }} />

        <Divider sx={{ width: "100%", display: { xs: "none", sm: "flex" } }} />

        <MenuLinks id={id} />
      </MenuWrapper>
      <Box
        sx={{
          p: "16px",
          paddingLeft: {
            xs: 0,
            sm: "112px", // 96px + 16px
            xl: "456px", // 440px + 16px
          },
        }}
      >
        {children}
      </Box>
    </>
  );
}
